[[DatabaseIdentifier]]
name = "mydb"

  [[DatabaseIdentifier.metric]]
  context = "slow_queries"
  metricsdesc = { p95_time_usecs= "Gauge metric with percentile 95 of elapsed time.", p99_time_usecs= "Gauge metric with percentile 99 of elapsed time." }
  cloudwatchtype = { p95_time_usecs = "Microseconds", p99_time_usecs = "Microseconds" }
  request = "select  percentile_disc(0.95)  within group (order by elapsed_time) as p95_time_usecs, percentile_disc(0.99)  within group (order by elapsed_time) as p99_time_usecs from v$sql where last_active_time >= sysdate - 5/(24*60)"
