name: Go

on:
  push:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Test
        run: |
          go build -v ./...
          go test -v ./...

      - name: prepare binary
        run: go build cmd/collector/main.go  -o database-collector

      - name: upload binary
        uses: actions/upload-artifact@v4
        with:
          name: database-collector
          path: database-collector
