name: Go

on:
  push:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Compile
        run: |
          cd collector
          go build -v ./...

      - name: Test
        run: |
          cd collector
          go test -v ./...

